# Generated by Django 5.0.1 on 2024-01-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_topico_options_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topico',
            name='visualizacao',
            field=models.IntegerField(default=0, verbose_name='Visualizações'),
        ),
    ]
