# Generated by Django 4.2.9 on 2024-01-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topico',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
